[package]
name = "libretro-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-libretro-sys = "0.3.2"
libloading = "0.8"

[dev-dependencies]
cargo_metadata = "0.19.1"
glob = "0.3.1"
rust-libretro-example-core = "0.3.2"
